### ISSUE TITLE
Cannot create block

### ISSUE THREAD

**Issue by IceandFire04** [JeremyGamer13/turbobuilder#2]
won't let me enter in an input or text

**Comment by qtqgyt** [comment]
this version is abandoned, jermey left turbobuilder

**Comment by mcnole25** [comment]
> this version is abandoned, jermey left turbobuilder

That's sad :(

**Comment by qtqgyt** [comment]
> > this version is abandoned, jermey left turbobuilder
> 
> That's sad :(

I think jklong took it over

**Comment by mcnole25** [comment]
> > > this version is abandoned, jermey left turbobuilder
> > 
> > 
> > That's sad :(
> 
> I think jklong took it over

Who is jklong? This project hasn't been updated yet
By the way, I made something called UnSandbox Block Maker and plan to develop it

**Comment by qtqgyt** [comment]
> > > > this version is abandoned, jermey left turbobuilder
> > > 
> > > 
> > > That's sad :(
> > 
> > 
> > I think jklong took it over
> 
> Who is jklong? This project hasn't been updated yet By the way, I made something called UnSandbox Block Maker and plan to develop it

No its on a different github repo
and the new url is [https://turbobuilder-steel.vercel.app/](https://turbobuilder-steel.vercel.app/)

**Comment by mcnole25** [comment]
> > > > > this version is abandoned, jermey left turbobuilder
> > > > 
> > > > 
> > > > That's sad :(
> > > 
> > > 
> > > I think jklong took it over
> > 
> > 
> > Who is jklong? This project hasn't been updated yet By the way, I made something called UnSandbox Block Maker and plan to develop it
> 
> No its on a different github repo and the new url is https://turbobuilder-steel.vercel.app/

Okay, cool :)

**Comment by qtqgyt** [comment]
This should be closed
